services:
  postgres:
    image: timescale/timescaledb:2.15.0-pg15
    restart: always
    environment:
      POSTGRES_USER: pollution
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pollutiondb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  data-collector:
    build:
      context: ./data-collector
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_USER_NAME: pollution
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_NAME: pollutiondb
    restart: on-failure

volumes:
  postgres_data:
  rabbitmq_data: